SELECT 
PFH.PRNUM, PFH.ISSUEDDATE, PFH.ISSUEDTIME, PFH.CURRENTUSER, PFH.NEXTUSER, PFH.VENDORID, PFH.VENDORNAME, PFH.SECTIONID, PFH.BUDGETTYPE, PFH.AMOUNT, PFH.TAXAMOUNT, PFH.TOTALAMOUNT, PFH.RELSTATEGY, PFH.[DESCRIPTION], PFH.REMARK, PFH.STATUS, PFH.CREATEDBY, PFH.CREATEDDATE, PFH.CREATEDTIME, PFH.EDITEDBY, PFH.EDITEDDATE, PFH.EDITEDTIME, PFH.ENABLED FROM TT_PRFORM PFH LEFT JOIN TT_PRFORM_LINE PFL ON PFL.PRNUM = PFH.PRNUM
  WHERE 
  PFH.STATUS IN ('ISSUE', 'ONLINE', 'PREAPPR', 'APPROVED', 'REJECTED') AND PFH.PRNUM NOT IN ('PR00000001','PR00000002')
  AND PFL.EXPENSEID = '55400-H100'
  ORDER BY PFH.PRNUM, PFL.ITEMNO ASC

