"select [PLANT], ROWID, PKLNUM, PKLROWID, CUSTID, RECSTORE, SHIPOPER, DELIDATE, SHIPDATE, SHIPTIME, CUSTNAME, SUPNAME, SAPARTNUM, CUSTPARTNUM, QPACK, QUANTITY, BOXQTY, PDSNUM, PARTNAME, ISSUEDATE, ISSUETIME, PACKED,
CASE
    WHEN STATUS = 'OK' THEN 'ALREADY SHOPPING'
    WHEN STATUS = 'PENDING' THEN 'NO SHOPPING'
    ELSE 'N/A'
  END AS STATUS
from 
(
select 'TMT' as [PLANT], ROWID, PKLNUM, PKLROWID, CUSTID, RECSTORE, SHIPOPER, DELIDATE, SHIPDATE, SHIPTIME, CUSTNAME, SUPNAME, SAPARTNUM, CUSTPARTNUM, QPACK, QUANTITY, BOXQTY, PDSNUM, PARTNAME, ISSUEDATE, ISSUETIME, PACKED, STATUS  from TM_PLAN_TMT
union all
select 'NON TMT' as [PLANT], ROWID, PKLNUM, PKLROWID, CUSTID, RECSTORE, SHIPOPER, DELIDATE, SHIPDATE, SHIPTIME, CUSTNAME, SUPNAME, SAPARTNUM, CUSTPARTNUM, QPACK, QUANTITY, BOXQTY, PDSNUM, PARTNAME, ISSUEDATE, ISSUETIME, PACKED, STATUS from TM_PLAN_OTHER
) x
WHERE x.PDSNUM = '1P SA11AP1H8853'
"
