select DATE_CHK, TIME_CHK, PDS_NUM, PART_NUM, PART_NAME, PART_SA, PACK_QTY, PACKED, USER_CHK from TM_LOG_OK where PDS_NUM = @PDSNO
select [DATE], [TIME], USER_NG, NG_DESCRIPTION, PDS_NUM, NG_ID, UNLOCK_NG from TM_LOG_NG where PDS_NUM = @PDSNO
select ROWID, FUNCTION_NAME, [DESCRIPTION], PDSNUM, CUSTPARTNUM, CREATEBY, CREATEDATE, CREATETIME from TT_EVENT_LOG where PDSNUM = @PDSNO
select RIDTTIFPO, PONUM, ITEMID, DOCTYPE, VENDORID, PAYMENTTERM, INCOTERM1, INCOTERM2, CURRENCYID, PURORG, PURGRP, COMPID, ISINVESTMENT, MATID, TXTCOMMENT, QUANTITY, UNIT, REQUIREDDATE, UNITPRICE, MATGRP, PLANT, VATID, DEPTID, GLACCOUNT, INVESTMENTID, PRODUCTID, MACHINEID, PRODUCTIONLINEID, REQUIREDBY, PODATE, CREATEDDATE, IFSTATUS, CARRYSTATUS, IFMESSAGE, OPTFIELD1, OPTFIELD2, OPTFIELD3, OPTFIELD4, OPTFIELD5, OPTFIELD6, OPTFIELD7 from TTIFPO where PONUM = 'PO15010548' order by PODATE
select 
RIDTTIFRC, RCDATE, SAPDOCNO, PONUM, ITEMID, INVNUM, POSTINGDATE, QUANTITY, STORELOC, LINEID, SECTIONID, IFSTATUS, IFMESSEGE, 
SAPMATDOCNO, SAPMATDOCYEAR, SAPITEMID, OPTFIELD1, OPTFIELD2, OPTFIELD3, OPTFIELD4, OPTFIELD5, OPTFIELD6, OPTFIELD7 
from TTIFREC 
where PONUM = @PONUM and 
INVNUM like '%'@INVNUM'%' 
order by postingdate, invnum

