select 
RIDTTIFPO, PONUM, ITEMID, DOCTYPE, VENDORID, PAYMENTTERM, INCOTERM1, INCOTERM2, CURRENCYID, PURORG, PURGRP, COMPID, ISINVESTMENT, MATID, TXTCOMMENT, QUANTITY, UNIT, REQUIREDDATE, UNITPRICE, MATGRP, PLANT, VATID, DEPTID, GLACCOUNT, INVESTMENTID, PRODUCTID, MACHINEID, PRODUCTIONLINEID, REQUIREDBY, PODATE, CREATEDDATE, IFSTATUS, CARRYSTATUS, IFMESSAGE, OPTFIELD1, OPTFIELD2, OPTFIELD3, OPTFIELD4, OPTFIELD5, OPTFIELD6, OPTFIELD7 
from TTIFPO 
where PONUM = 'PO15010548' 
order by PODATE
