select 
RIDTTIFRC, RCDATE, SAPDOCNO, PONUM, ITEMID, INVNUM, POSTINGDATE, QUANTITY, STORELOC, LINEID, SECTIONID, IFSTATUS, IFMESSEGE, SAPMATDOCNO, SAPMATDOCYEAR, SAPITEMID, OPTFIELD1, OPTFIELD2, OPTFIELD3, OPTFIELD4, OPTFIELD5, OPTFIELD6, OPTFIELD7 
from TTIFREC 
where PONUM = @PONUM and 
INVNUM like '%'@INVNUM'%' 
order by postingdate, invnum
