select 
RIDTTINV, INVDATE, INVNUM, PONUM, ITEMID, POSTINGDATE, TOTAMT, TAXAMT, BUSPLACE, [DESCRIPTION], QUANTITY, CREATEDDATE, IFSTATUS, IFMESSEGE, SAPINVDOC, SAPINVDOCYEAR, SAPINVITEMID, OPTFIELD1, OPTFIELD2, OPTFIELD3, OPTFIELD4, OPTFIELD5, OPTFIELD6, OPTFIELD7 
from TTIFINV 
where PONUM = @PONUM and
INVNUM like '%'@INVNUM'%' 
order by postingdate, invnum
